# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    pre:
      - echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v7-dependency-cache-{{ checksum "package-lock.json" }}
            - v7-dependency-cache
      - run: npm install
      - save_cache:
          key: v7-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: '.'
          paths:
            - package-lock.json
  test:
    parallelism: 4
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: v7-dependency-cache-{{ checksum "package-lock.json" }}
      - run: sudo npm i -g lerna
      - run:
          command: |
            case $CIRCLE_NODE_INDEX in \
            0) npm test -- --scope '@clickopolis/app' ;;\
            1) npm test -- --scope '@clickopolis/core' ;;\
            2) npm test -- --scope '@clickopolis/mobile' ;;\
            3) npm test -- --scope '@clickopolis/server' ;;\
            4) npm test -- --scope '@clickopolis/webpack-build-scripts' ;;\
            esac
  deploy_npm:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm i semver
      - attach_workspace:
          at: '.'
      - restore_cache:
          key: v7-dependency-cache-{{ checksum "package-lock.json" }}
      - run: echo "It would normally deploy here."

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy_npm:
          filters:
            branches:
              only:
                - master
                - /^release\.*/